### ISSUE TITLE
Traffic is not working

### ISSUE THREAD

**Issue by biglimp** [Urban-Meteorology-Reading/GQF-PYQGIS3#2]
All values are 0 in output csv-tables. Occuring in the disaggregate function.

**Comment by sunt05** [comment]
resolved by updating several deprecated APIs: c40157714ed6d127072eaa7d4d9395a653129f18
The `multilinestring` was the issue that caused no traffic was logged in the calculation.

 I feel there might be more issues to resolve for the QGIS3 environment but I now get a slightly better understanding of the *mysterious QGIS myriad*: all wonders can happen!

**Comment by sunt05** [comment]
Will check with Izzy to see if the non-zero results are meaningful; then we can close this issue.

**Comment by biglimp** [comment]
I can also test but I am having trouble getting in down from Github. I originally forked and cloned you repo. Now I can only access my cloned one but now yours. please help...

**Comment by sunt05** [comment]
can you `pull`?

**Comment by sunt05** [comment]
> I can also test but I am having trouble getting in down from Github. I originally forked and cloned you repo. Now I can only access my cloned one but now yours. please help...

can you `pull`?

**Comment by biglimp** [comment]
Yes, but only my version. I fixed temporally by downloading it as a zip.

**Comment by sunt05** [comment]
Just get you on board as a collaborator of this repo so you should be able to sync updates directly here.

**Comment by biglimp** [comment]
Ok thanks.
Got an pandas error. Using version 0.23.4

> An error has occurred while executing Python code: 
> 
> TypeError: Cannot convert input [DatetimeIndex(['2015-01-01 00:30:00'], dtype='datetime64[ns]', freq=None)] of type to Timestamp 
> Traceback (most recent call last):
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\greater_qf.py", line 407, in startWorker
>     self.model.run() #TODO Moved it outside to find error
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\GreaterQF.py", line 202, in run
>     self.mostcalcs()
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\GreaterQF.py", line 242, in mostcalcs
>     freq='30Min')
>   File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\datetimes.py", line 2749, in date_range
>     closed=closed, **kwargs)
>   File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\datetimes.py", line 381, in __new__
>     ambiguous=ambiguous)
>   File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\datetimes.py", line 476, in _generate
>     start = Timestamp(start)
>   File "pandas\_libs\tslibs\timestamps.pyx", line 644, in pandas._libs.tslibs.timestamps.Timestamp.__new__
>   File "pandas\_libs\tslibs\conversion.pyx", line 309, in pandas._libs.tslibs.conversion.convert_to_tsobject
> TypeError: Cannot convert input [DatetimeIndex(['2015-01-01 00:30:00'], dtype='datetime64[ns]', freq=None)] of type  to Timestamp

**Comment by sunt05** [comment]
That's the same issue as you did when running under QGIS/UMEP.
Just set up a `try/except` to bypass this for the UMEP scenario.

**Comment by sunt05** [comment]
> Not sure I follow. Where should the try/except be located?

see here: 226a74ef4e7feae9c5533cc72d6940c4a7f4b4d3

You might need some tweaks as I don't know how to debug this within QGIS GUI environment.

**Comment by biglimp** [comment]
Ok fixed that. NOw another pandas issue:

> An error has occurred while executing Python code: 
> 
> KeyError: NaT 
> Traceback (most recent call last):
>   File "pandas\_libs\index.pyx", line 447, in pandas._libs.index.DatetimeEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 958, in pandas._libs.hashtable.Int64HashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 964, in pandas._libs.hashtable.Int64HashTable.get_item
> KeyError: -9223372036854775808
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\greater_qf.py", line 407, in startWorker
>     self.model.run() #TODO Moved it outside to find error
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\GreaterQF.py", line 202, in run
>     self.mostcalcs()
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\GreaterQF.py", line 324, in mostcalcs
>     dailyE, pop, trans, diurnalT, hap, df,  props, self.parameters.heatOfCombustion)
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\Calcs3.py", line 72, in QF
>     dailyEnergy.getElec(timeStepEnd, timeStepDuration)[0] * \
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\DailyEnergyLoading.py", line 41, in getElec
>     return self.electricity.getValueForDateTime(requestDateTime, timeBinDuration)
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\DataManagement\GenericAnnualSampler.py", line 393, in getValueForDateTime
>     (extracted, timestamp, dayofweek) = self.extractCorrectEntry(df, timeBinEnd, timeBinDuration, dowNeeded)
>   File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\GreaterQF\PythonQF2\DataManagement\DailyLoading.py", line 88, in extractCorrectEntry
>     return (df[mostRecent], mostRecent, wd)
>   File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\series.py", line 767, in __getitem__
>     result = self.index.get_value(self, key)
>   File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\datetimes.py", line 1556, in get_value
>     return self.get_value_maybe_box(series, key)
>   File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\indexes\datetimes.py", line 1584, in get_value_maybe_box
>     key, tz=self.tz)
>   File "pandas\_libs\index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
>   File "pandas\_libs\index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
>   File "pandas\_libs\index.pyx", line 449, in pandas._libs.index.DatetimeEngine.get_loc
> KeyError: NaT

**Comment by sunt05** [comment]
I just left my office. 
Looks like still a datetime type issue. 
Maybe worth checking your input datetime type at the beginning, i.e. in configuration. 
Then decide how to convert it to a pandas-friendly one.
