### ISSUE TITLE
datetime issue with UMEP

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/GQF-PYQGIS3#4]
@biglimp 
Have a look here when you load the dates in via UMEP/QGIS GUI settings:
https://github.com/Urban-Meteorology-Reading/GQF-PYQGIS3/blob/889a891605c500a70318c9c705bb1f67fae4da8c/GQF/GreaterQF.py#L223-L248

Make sure your loaded `startDates` and `endDates` can be properly picked up by `pd.date_range`.

As I don't have GQF installed in QGIS, I cannot help too much there.

**Comment by sunt05** [comment]
related posts:
https://github.com/Urban-Meteorology-Reading/GQF-PYQGIS3/issues/2#issuecomment-491326917

**Comment by biglimp** [comment]
solved
